[package]
name = "dynamic-apr"
version = "0.1.0"
edition = "2018"
license = "WTFPL"
publish = false

[dependencies]
solana-program = "=1.8.1"
borsh = "0.9.1"
spl-token = { version="3.2", features = [ "no-entrypoint" ] }
thiserror = "1.0.24"

[lib]
crate-type = ["cdylib", "lib"]
